# YML HAS PRIORITY OVER PROGRAMMATIC CONFIG
resilience4j:
  circuitbreaker:
    configs:
      default: # This is the name of config (can be anything)
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15s
        permitted-number-of-calls-in-half-open-state: 4
        slow-call-duration-threshold: 3s
        slow-call-rate-threshold: 50
    instances:
      products: # THIS NAME IS PROVIDED IN CONTROLLER
        base-config: default

  timelimiter:
    configs:
      default: # This is the name is of your choice
        timeout-duration: 3s
    instances:
      products:
        base-config: default

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: msvc-products
          uri: lb://msvc-products
          predicates:
            # ALL THESE CONDITIONS ARE REQUIRED
            - Path=/api/products/**
            - Header=token, \d+
#            - Method=GET,POST
#            - Query=color, green
#            - Cookie=color, blue
#            - Header=Content-Type, application/json
          filters:
            - name: CircuitBreaker
              args:
                name: products
                statusCodes: 500
                fallbackUri: forward:/api/items/1
            - StripPrefix=0
#            CUSTOM FILTERS METHOD 1
#            - name: SampleCookie
#              args:
#                message: Hi, this is my custom message for products
#                name: user
#                value: KleeCollage
#            CUSTOM FILTERS METHOD 2 according to our class: msg, name, value
            - ExampleCookie=Hi this is my custom message for products, user, KleeC
        - id: msvc-items
          uri: lb://msvc-items
          predicates:
            - Path=/api/items/**
          filters:
            - StripPrefix=0
#            - StripPrefix=1 -> REMOVE /api from path
#            - StripPrefix=2 -> REMOVE /api/items from path
            - AddRequestHeader=token-request, Xyz789
            - AddResponseHeader=token-response, Ijk456
            - AddRequestParameter=name, KleeC
            - SetResponseHeader=Content-Type, text/plain
